### PR TITLE
add R team

### PR DESCRIPTION
**Pull request by mfansler**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
@conda-forge/core please merge

[Request was made](https://github.com/conda-forge/r-buildmer-feedstock/pull/2#issuecomment-1606887813) to maintainer three weeks ago.

**Comment by beckermr** [comment]
I'm happy to merge but please be aware that this will have the side effect of adding bot automerge to this feedstock for R migrations and version updates.

**Comment by jakirkham** [comment]
Yeah I think that is how the R team prefers to manage things. This helps move the periodic R version migrations quickly

**Comment by mfansler** [comment]
> I'm happy to merge but please be aware that this will have the side effect of adding bot automerge to this feedstock for R migrations and version updates.

Thanks for the heads up. Yes, that's fine.

**Pull request merged**
